spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: lk5as1gb0
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    naming: 
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT+7
    default-property-inclusion: NON_NULL